### ISSUE TITLE
Make teleporting through doors faster

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/PWMod#114]
Make teleporting through doors faster

**Comment by Thomas-Smyth** [comment]
@WilliamPhoenix need a better explanation of how this should be done.

**Comment by WilliamPhoenix** [comment]
This will obviously affect the balance of sieges and should be thought about carefully. Making it too fast or even changing it slightly could have a negative effect. Needs to be discussed.

**Comment by Thomas-Smyth** [comment]
@WilliamPhoenix I don't think the time can be decreased. I tried to change it from one to 0.5 and it didn't like it because it's not an integer and obviously 0 would be a bit OP.

**Comment by WilliamPhoenix** [comment]
Alright.
