### ISSUE TITLE
Fast inventory transfer

### ISSUE THREAD

**Issue by Saptortacus** [SmartPhoenix/PWMod#137]
### Specification/Explicit TODO
When a player opens an inventory, if he right clicks on an item he equips or an item to be eqipped, it will automatically equip/unequip it.

**Comment by WilliamPhoenix** [comment]
Changed to just "right click" and not swapping the items. The person first needs to unequip the item by pressing right click on it and then equip the new item by right-clicking on it.

**Comment by WilliamPhoenix** [comment]
Implemented.
