### ISSUE TITLE
Arrow limit per arrow type

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/PWMod#25]
Make it so that better arrows have smaller quivers like you can see in mercs.
30 Bent Arrows, 30 Arrows, 27 Barbed Arrows, 24 Bodkin Arrows, 24 Broadhead Arrows

**Comment by WilliamPhoenix** [comment]
Still unsure on what to do with bolts.

**Comment by Thomas-Smyth** [comment]
Changes made in `ta-ammo-amounts` branch. Requires testing and review.
