### ISSUE TITLE
Flags Above Players

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/PWMod#28]
Take a look into making it optional to switch between player names/flags above players/nothing.

**Comment by WilliamPhoenix** [comment]
https://forums.taleworlds.com/index.php/topic,266022.msg6378807.html#msg6378807
Not possible.

**Comment by Thomas-Smyth** [comment]
https://i.gyazo.com/a337248ada5f90a07cceae7dd8bbbae8.png

**Comment by Thomas-Smyth** [comment]
Basic Name Labels implemented.
