### ISSUE TITLE
Add new castle names

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/PWMod#32]
Making a new mod allows you to change this at last. Custom names could be added for the settlements in maps such as the North, Westeros, Skyrim (maps based on something).
A thread has been made for that so people can suggest castle names.

**Comment by Thomas-Smyth** [comment]
@DekkersNL once you have compiled a list of castles you want to be removed / added send them to me and I'll add them. Try and group the castle names with similar themes together in that list, please.

**Comment by WilliamPhoenix** [comment]
Added.
