### ISSUE TITLE
Can default wars be prevented?

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/PWMod#42]
Can default wars be prevented?

**Comment by WilliamPhoenix** [comment]
Quote from: QWW on August 29, 2013, 09:12:54 AM
I've been having some trouble finding the code that starts the factions at war. I'd like them to be all at peace. Can you point me in the right direction?

Nothing starts them at "war", that's simply the default state - a faction slot has to be changed from the initial 0 for lords to agree to have peace between their factions. For this combat game, "war" is the normal relationship between factions, with "peace" just for agreements by lords to work together, treating kills between members as the same team (the only difference). "War" is the only relationship suitable with independent players (commoners, outlaws) because they have no responsibility or accountability to anyone else - otherwise lone commoners could steal from, block access, or otherwise interfere with a faction, which would somehow get in trouble with an invisible "global police force" just for defending their property; and getting an outlaw rating for attacking an outlaw makes absolutely no sense.

The relevant slots are an array starting at slot_faction_relations_begin, adding the other faction id to get the relationship to them (the relationship from is set in a corresponding slot of the other faction). See script cf_factions_are_hostile or cf_faction_admin_action.

**Comment by Thomas-Smyth** [comment]
https://github.com/SmartPhoenix/PWMod/pull/55

**Comment by WilliamPhoenix** [comment]
Tested. Works.
