### ISSUE TITLE
[LOGS] Show damage as healing with scalpel

### ISSUE THREAD

**Issue by Thomas-Smyth** [SmartPhoenix/PWMod#49]
[LOGS] Show damage as healing with scalpel

**Comment by Thomas-Smyth** [comment]
@LuisEngelniederhammer, mind looking through this with me sometime? I have some questions you might be able to answer.

**Comment by LuisEngelniederhammer** [comment]
@Thomas-Smyth of course, on saturday or sunday if you want

**Comment by Thomas-Smyth** [comment]
@LuisEngelniederhammer you around Sunday evening? I'm going away briefly today and tomorrow (should get back mid-afternoon).

**Comment by WilliamPhoenix** [comment]
Attack logs need to be adjusted to not show double logs.
