### ISSUE TITLE
Marshall Role ?

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/PWMod#70]
Marshall is assigned by the lord.
- Mute/unmute player
- Manage door keys
- Manage item chest keys
Pay attention that marshalls can't kick lords or other marshalls.
Marshalls receive door keys, item chest keys, ability to announce stuff immediately.

**Comment by Thomas-Smyth** [comment]
I have created a branch for this task.

I've added the basic functionality, however, it has had zero testing as I need someone to test it with me.

**Comment by WilliamPhoenix** [comment]
Tested. Works.
