### ISSUE TITLE
Log System

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/PWMod#75]
Add attack logs

**Comment by WilliamPhoenix** [comment]
Pay attention to healing logs (double attacks).
It would also be nice to include the weapon used in the attack.

**Comment by LuisEngelniederhammer** [comment]
Another specification for this task:
The attack logs will replace the existing attack logs currently in place, therefore we have the liberty to add more detail to them.

**Comment by WilliamPhoenix** [comment]
Update on the issue. We've decided to put the whole log system into the module.
That includes all the following logs: http://eu.pw-phoenix.com/servers/1/logs//server_log_03_08_18.txt

Added already or in a separate issue:
- Mount/Dismount a horse
- Attacking shields
- When castle gets captured
- When a faction changes the name

Changes to the current log system:
- Include the weapon used in the attack.
- Add logs of lords&marshals kicking&outlawing people.
