### ISSUE TITLE
Fix admin logs

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/PWMod#77]
Tommy, I think the logs are still meant "for the older system". For example, when I go "godlike" it says I spawned an admin horse etc. I believe that's connected with your re-ordering. Have a look, please.

**Comment by Thomas-Smyth** [comment]
https://github.com/SmartPhoenix/PWMod/pull/78

**Comment by WilliamPhoenix** [comment]
Tested. Works.
