### ISSUE TITLE
[LOG] Equipment on log in & log out

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/PWMod#85]
We need logs to show the equipment of people when they log in or log out for refund requests and server crashes.

**Comment by LuisEngelniederhammer** [comment]
That has to be implemented into the "left server" logs

**Comment by Thomas-Smyth** [comment]
@Saptortacus 
https://i.gyazo.com/35f78ae41a727f689878bc28ea250f62.png
