### ISSUE TITLE
List members of inactive factions in admin tools

### ISSUE THREAD

**Issue by Thomas-Smyth** [SmartPhoenix/PWMod#86]
Currently, people that are in factions that are disabled on the current map cannot be selected in the admin menu. They need to be added to ensure that they can be selected.

**Comment by Saptortacus** [comment]
or assign them to Commoners!

**Comment by Thomas-Smyth** [comment]
The current one has been merged, however, we found that when disconnecting or respawning you keep your class when in commoner.

**Comment by WilliamPhoenix** [comment]
Solved.
